name: CMake

on:
  push:
    tags:        
      - '*'

jobs:
  build-windows-win32-vs2017:
    name: Win32 (Windows, VS2017)
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Checkout LFS objects
        run: |
          git lfs pull
          git lfs checkout

      - name: Configure CMake Debug
        run: cmake -B ${{github.workspace}}/Build/Debug -G "Visual Studio 15 2017" -A Win32 -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/Install/Debug
      - name: Build Debug
        run: cmake --build ${{github.workspace}}/Build/Debug --config DEBUG --target install
      
      - name: Configure CMake MinSizeRel
        run: cmake -B ${{github.workspace}}/Build/MinSizeRel -G "Visual Studio 15 2017" -A Win32 -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/Install/MinSizeRel
      - name: Build MinSizeRel
        run: cmake --build ${{github.workspace}}/Build/MinSizeRel --config MINSIZEREL --target install

      - uses: actions/upload-artifact@master
        with:
          name: win32
          path: |
            ${{github.workspace}}/Install/Debug
            ${{github.workspace}}/Install/MinSizeRel

  build-windows-win64-vs2017:
    name: Win64 (Windows, VS2017)
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Checkout LFS objects
        run: |
          git lfs pull
          git lfs checkout

      - name: Configure CMake Debug
        run: cmake -B ${{github.workspace}}/Build/Debug -G "Visual Studio 15 2017" -A x64 -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/Install/Debug
      - name: Build Debug
        run: cmake --build ${{github.workspace}}/Build/Debug --config DEBUG --target install
      
      - name: Configure CMake MinSizeRel
        run: cmake -B ${{github.workspace}}/Build/MinSizeRel -G "Visual Studio 15 2017" -A x64 -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/Install/MinSizeRel
      - name: Build MinSizeRel
        run: cmake --build ${{github.workspace}}/Build/MinSizeRel --config MINSIZEREL --target install

      - uses: actions/upload-artifact@master
        with:
          name: win64
          path: |
            ${{github.workspace}}/Install/Debug
            ${{github.workspace}}/Install/MinSizeRel

  build-macos-cocoa-clang:
    name: Cocoa (macOS, Clang)
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.15
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Checkout LFS objects
        run: |
          git lfs pull
          git lfs checkout

      - name: Configure CMake Debug
        run: cmake -B ${{github.workspace}}/Build/Debug -G Xcode -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/Install/Debug
      - name: Build Debug
        run: cmake --build ${{github.workspace}}/Build/Debug --config DEBUG --target install
      
      - name: Configure CMake MinSizeRel
        run: cmake -B ${{github.workspace}}/Build/MinSizeRel -G Xcode -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/Install/MinSizeRel
      - name: Build MinSizeRel
        run: cmake --build ${{github.workspace}}/Build/MinSizeRel --config MINSIZEREL --target install

      - uses: actions/upload-artifact@master
        with:
          name: darwin
          path: |
            ${{github.workspace}}/Install/Debug
            ${{github.workspace}}/Install/MinSizeRel

  release:
    name: Release
    needs: [build-windows-win32-vs2017, build-windows-win64-vs2017, build-macos-cocoa-clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Checkout LFS objects
        run: |
          git lfs pull
          git lfs checkout

      - uses: actions/download-artifact@master
        with:
          name: win32
          path: ${{github.workspace}}/release/win32/x86

      - uses: actions/download-artifact@master
        with:
          name: win64
          path: ${{github.workspace}}/release/win32/x64
      
      - uses: actions/download-artifact@master
        with:
          name: darwin
          path: ${{github.workspace}}/release/darwin

      - name: Zip
        run: cd ${{github.workspace}}/release && zip -vr ${{github.workspace}}/release.zip ./ && cd ${{github.workspace}}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          name: ${{ steps.version.outputs.version }}
          files: ${{github.workspace}}/release.zip
      
